1.Load the patient dataset and show summary with info().

In [2]:
import pandas as pd
df = pd.read_csv('Patient_Data.csv')
df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [3]:
df.shape

(6, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 464.0+ bytes

In [5]:
df.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

2.Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [6]:
df[['PatientID','Department','Doctor','BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

3.Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [7]:
df.drop(['ReceptionistID','CheckInTime'],axis = 1)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.Use groupby to find total bill amount per department.

In [8]:
df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.Remove duplicate patient records based on PatientID.

In [9]:
df['PatientID'].duplicated().sum()

np.int64(1)

6.Fill missing BillAmount values with the mean bill amount.

In [10]:
clean_data = df.drop_duplicates(subset = 'PatientID')
clean_data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [11]:
amount_mean = df['BillAmount'].mean()
amount_mean

np.float64(5925.0)

In [12]:
df['BillAmount'] = df['BillAmount'].fillna(amount_mean)

In [13]:
clean_data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [14]:
billing_df = pd.read_csv('Billing_Data.csv')

7.Merge the billing dataset with patient dataset on PatientID.

In [15]:
merged_df = pd.merge(clean_data, billing_df, on='PatientID')

In [16]:
merged_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45,1000,4000

    8.Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
    9.Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [18]:
new_patient_df = pd.DataFrame({
    'PatientID':[106,107],
    'Name':['Devi Vara Prasad','Jyothinadh'],
    'Department':['Neurology','Orthopedics'],
    'Doctor':['Dr. Sharma','Dr. Rao'],
    'BillAmount':[5000,6000],
    'ReceptionistID':[4,5],
    'CheckInTime':['2026-06-12','2026-06-13'],
    'InsuranceCovered':[2000,3000],
    'FinalAmount':[3000,3000]
})

updated_df = pd.concat([merged_df,new_patient_df],axis = 0,ignore_index = True)
updated_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45,1000,4000
5,106,Devi Vara Prasad,Neurology,Dr. Sharma,5000.0,4,2026-06-12,2000,3000
6,107,Jyothinadh,Orthopedics,Dr. Rao,6000.0,5,2026-06-13,3000,3000